version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    open-pull-requests-limit: 10
    groups:
      aksel:
        patterns:
          - "@navikt/aksel-*"
          - "@navikt/ds-*"
      react:
        patterns:
          - "react"
          - "react-dom"
      minor-and-patch:
        update-types:
          - "patch"
          - "minor"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "@navikt/aksel-*"
          - "@navikt/ds-*"

  - package-ecosystem: "npm"
    directory: "/server"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    groups:
      npm:
        patterns:
          - "*"
