version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: weekly
      day: "monday"
      time: "06:00"
      timezone: "Europe/Oslo"
    groups:
      npm:
        patterns:
          - "*"