version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      timezone: "Europe/Oslo"
    groups:
      npm:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: "/server"
    schedule:
      interval: daily
      timezone: "Europe/Oslo"
    groups:
      npm:
        patterns:
          - "*"