apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sokos-mikrofrontend-template
  namespace: okonomi
  labels:
    team: okonomi
spec:
  envFrom:
    - secret: sokos-mikrofrontend-template-secrets
  image: {{ image }}
  port: 7100
  liveness:
    path: /sokos-mikrofrontend-template/internal/isAlive
    initialDelay: 10
  readiness:
    path: /sokos-mikrofrontend-template/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /sokos-mikrofrontend-template/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://sokos-mikrofrontend-template.dev.nav.no/sokos-mikrofrontend-template"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
