name: Bygg og test PR

on:
  pull_request:
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  build-pull-request:
    name: Bygg og test
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut repo
        uses: actions/checkout@v3

      - name: Installerer node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installere pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Hente pnpm store mappe
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setter opp pnpm cache for klient
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setter opp pnpm cache for server
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('server/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installerer dependencies
        run: pnpm install

      - name: Installerer dependencies for server
        run: cd server && pnpm install

      - name: Bygger applikasjonen
        run: pnpm run build