name: Dependabot auto-merge
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENCE"
      - "CODEOWNERS"
      - ".gitignore"
      - ".github/workflows/deploy.yaml"
      - ".github/workflows/manual-deploy-dev.yaml"
      - ".github/workflows/playwright.yaml"
      - ".github/workflows/security.yaml"
      - ".github/dependabot.yaml"

jobs:
  dependabot-automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Dependabot auto-merge
    uses: navikt/mob-gha-workflows/.github/workflows/dependabot-automerge.yaml@main
    secrets: inherit
