name: Dependabot auto-merge
on: pull_request

jobs:
  dependabot-automerge:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    name: Dependabot auto-merge
    uses: navikt/mob-gha-workflows/.github/workflows/dependabot-automerge.yaml@main
    secrets: inherit
